export const restaurants = [
  {
    id: 1,
    name: 'Spice Garden',
    image: `${process.env.PUBLIC_URL}/images/Restaurants/restaurant1.webp`,
    menu: [
      { name: 'Paneer Tikka', price: 60, image: `${process.env.PUBLIC_URL}/images/FoodItems/paneer.jpg` },
      { name: 'Butter Naan', price: 40, image: `${process.env.PUBLIC_URL}/images/FoodItems/naan.jpg` },
      { name: 'Royal Thali', price: 250, image: `${process.env.PUBLIC_URL}/images/FoodItems/thali.jpg` },
      { name: 'Aloo Gobi', price: 60, image: `${process.env.PUBLIC_URL}/images/FoodItems/aloo_gobi.jpg` },
      { name: 'Dal Makhani', price: 50, image: `${process.env.PUBLIC_URL}/images/FoodItems/dal.jpg` },
      { name: 'Veg Biryani', price: 99, image: `${process.env.PUBLIC_URL}/images/FoodItems/veg_biryani.jpg` },
      { name: 'Kadai Mushroom', price: 60, image: `${process.env.PUBLIC_URL}/images/FoodItems/mushroom.jpg` },
      { name: 'Jeera Rice', price: 50, image: `${process.env.PUBLIC_URL}/images/FoodItems/jeera_rice.jpg` },
      { name: 'Tandoori Roti', price: 60, image: `${process.env.PUBLIC_URL}/images/FoodItems/roti.jpg` },
      { name: 'Malai Kofta', price: 230, image: `${process.env.PUBLIC_URL}/images/FoodItems/kofta.jpg` },
    ],
    mostPopular: [
      { name: 'Royal Thali', price: 250, image: `${process.env.PUBLIC_URL}/images/FoodItems/thali.jpg` },
      { name: 'Shahi Paneer', price: 210, image: `${process.env.PUBLIC_URL}/images/FoodItems/shahi_paneer.jpg` },
      { name: 'Malai Kofta', price: 230, image: `${process.env.PUBLIC_URL}/images/FoodItems/kofta.jpg` },
    ],
  },
  {
    id: 2,
    name: 'Ocean Bites',
    image: `${process.env.PUBLIC_URL}/images/Restaurants/restaurant2.jpg`,
    menu: [
      { name: 'Grilled Salmon', price: 250, image: `${process.env.PUBLIC_URL}/images/FoodItems/salmon.jpg` },
      { name: 'Garlic Shrimp', price: 230, image: `${process.env.PUBLIC_URL}/images/FoodItems/shrimp.jpg` },
      { name: 'Seafood Platter', price: 220, image: `${process.env.PUBLIC_URL}/images/FoodItems/seafood.jpg` },
      { name: 'Fish Curry', price: 140, image: `${process.env.PUBLIC_URL}/images/FoodItems/fish_curry.jpg` },
      { name: 'Crab Masala', price: 210, image: `${process.env.PUBLIC_URL}/images/FoodItems/crab.jpg` },
      { name: 'Prawn Fry', price: 130, image: `${process.env.PUBLIC_URL}/images/FoodItems/prawn.jpg` },
      { name: 'Lemon Fish', price: 120, image: `${process.env.PUBLIC_URL}/images/FoodItems/lemon_fish.jpg` },
      { name: 'Tuna Cutlet', price: 110, image: `${process.env.PUBLIC_URL}/images/FoodItems/tuna.jpg` },
      { name: 'Squid Rings', price: 125, image: `${process.env.PUBLIC_URL}/images/FoodItems/squid.jpg` },
      { name: 'Fish Fingers', price: 100, image: `${process.env.PUBLIC_URL}/images/FoodItems/fingers.jpg` },
      { name: 'Butter Garlic Crab', price: 240, image: `${process.env.PUBLIC_URL}/images/FoodItems/butter_crab.jpg` },
    ],
    mostPopular: [
      { name: 'Grilled Salmon', price: 250, image: `${process.env.PUBLIC_URL}/images/FoodItems/salmon.jpg` },
      { name: 'Seafood Platter', price: 220, image: `${process.env.PUBLIC_URL}/images/FoodItems/seafood.jpg` },
      { name: 'Butter Garlic Crab', price: 240, image: `${process.env.PUBLIC_URL}/images/FoodItems/butter_crab.jpg` },
    ],
  },
  {
    id: 3,
    name: 'Veggie Delight',
    image: `${process.env.PUBLIC_URL}/images/Restaurants/restaurant3.jpg`,
    menu: [
      { name: 'Veg Burger', price: 120, image: `${process.env.PUBLIC_URL}/images/FoodItems/burger.jpg` },
      { name: 'French Fries', price: 90, image: `${process.env.PUBLIC_URL}/images/FoodItems/fries.jpg` },
      { name: 'Stuffed Veg Lasagna', price: 250, image: `${process.env.PUBLIC_URL}/images/FoodItems/lasagna.jpg` },
      { name: 'Corn Salad', price: 80, image: `${process.env.PUBLIC_URL}/images/FoodItems/corn_salad.jpg` },
      { name: 'Grilled Sandwich', price: 130, image: `${process.env.PUBLIC_URL}/images/FoodItems/sandwich.jpg` },
      { name: 'Veg Wrap', price: 110, image: `${process.env.PUBLIC_URL}/images/FoodItems/wrap.jpg` },
      { name: 'Cheese Balls', price: 140, image: `${process.env.PUBLIC_URL}/images/FoodItems/cheese_balls.jpg` },
      { name: 'Spinach Pasta', price: 210, image: `${process.env.PUBLIC_URL}/images/FoodItems/spinach_pasta.jpg` },
      { name: 'Veg Cutlet', price: 100, image: `${process.env.PUBLIC_URL}/images/FoodItems/cutlet.jpg` },
      { name: 'Paneer Steak', price: 230, image: `${process.env.PUBLIC_URL}/images/FoodItems/paneer_steak.jpg` },
    ],
    mostPopular: [
      { name: 'Stuffed Veg Lasagna', price: 250, image: `${process.env.PUBLIC_URL}/images/FoodItems/lasagna.jpg` },
      { name: 'Paneer Steak', price: 230, image: `${process.env.PUBLIC_URL}/images/FoodItems/paneer_steak.jpg` },
      { name: 'Spinach Pasta', price: 210, image: `${process.env.PUBLIC_URL}/images/FoodItems/spinach_pasta.jpg` },
    ],
  },
  {
    id: 4,
    name: 'Tandoori Flames',
    image: `${process.env.PUBLIC_URL}/images/Restaurants/restaurant4.jpg`,
    menu: [
      { name: 'Chicken Tandoori', price: 250, image: `${process.env.PUBLIC_URL}/images/FoodItems/tandoori.jpg` },
      { name: 'Mint Chutney', price: 30, image: `${process.env.PUBLIC_URL}/images/FoodItems/chutney.jpg` },
      { name: 'Tandoori Mixed Grill', price: 240, image: `${process.env.PUBLIC_URL}/images/FoodItems/grill.jpg` },
      { name: 'Chicken Seekh Kebab', price: 220, image: `${process.env.PUBLIC_URL}/images/FoodItems/seekh.jpg` },
      { name: 'Tandoori Wings', price: 210, image: `${process.env.PUBLIC_URL}/images/FoodItems/wings.jpg` },
      { name: 'Spicy Drumsticks', price: 130, image: `${process.env.PUBLIC_URL}/images/FoodItems/drumsticks.jpg` },
      { name: 'Tandoori Fish', price: 140, image: `${process.env.PUBLIC_URL}/images/FoodItems/tandoori_fish.jpg` },
      { name: 'Stuffed Kulcha', price: 120, image: `${process.env.PUBLIC_URL}/images/FoodItems/kulcha.jpg` },
      { name: 'Masala Corn', price: 80, image: `${process.env.PUBLIC_URL}/images/FoodItems/masala_corn.jpg` },
      { name: 'Chicken Tikka Roll', price: 135, image: `${process.env.PUBLIC_URL}/images/FoodItems/tikka_roll.jpg` },
      { name: 'Tandoori Paneer', price: 230, image: `${process.env.PUBLIC_URL}/images/FoodItems/tandoori_paneer.jpg` },
    ],
    mostPopular: [
      { name: 'Chicken Tandoori', price: 250, image: `${process.env.PUBLIC_URL}/images/FoodItems/tandoori.jpg` },
      { name: 'Tandoori Mixed Grill', price: 240, image: `${process.env.PUBLIC_URL}/images/FoodItems/grill.jpg` },
      { name: 'Tandoori Paneer', price: 230, image: `${process.env.PUBLIC_URL}/images/FoodItems/tandoori_paneer.jpg` },
    ],
  },
   {
    id: 5,
    name: 'Sizzler Station',
    image: `${process.env.PUBLIC_URL}/images/Restaurants/restaurant5.jpg`,
    menu: [
      { name: 'Mixed Sizzler', price: 250, image: `${process.env.PUBLIC_URL}/images/FoodItems/sizzler.jpg` },
      { name: 'Corn on the Cob', price: 60, image: `${process.env.PUBLIC_URL}/images/FoodItems/corn.jpg` },
      { name: 'Smoky BBQ Platter', price: 240, image: `${process.env.PUBLIC_URL}/images/FoodItems/bbq.jpg` },
      { name: 'Grilled Chicken Sizzler', price: 230, image: `${process.env.PUBLIC_URL}/images/FoodItems/grilled_chicken.jpg` },
      { name: 'Veg Sizzler Bowl', price: 130, image: `${process.env.PUBLIC_URL}/images/FoodItems/veg_bowl.jpg` },
      { name: 'Paneer Sizzler', price: 220, image: `${process.env.PUBLIC_URL}/images/FoodItems/paneer_sizzler.jpg` },
      { name: 'Spicy Rice Sizzler', price: 140, image: `${process.env.PUBLIC_URL}/images/FoodItems/spicy_rice.jpg` },
      { name: 'Cheesy Potato Sizzler', price: 120, image: `${process.env.PUBLIC_URL}/images/FoodItems/potato.jpg` },
      { name: 'BBQ Sausage', price: 210, image: `${process.env.PUBLIC_URL}/images/FoodItems/sausage.jpg` },
      { name: 'Grilled Veggies', price: 100, image: `${process.env.PUBLIC_URL}/images/FoodItems/veggies.jpg` },
      { name: 'Mushroom Sizzler', price: 135, image: `${process.env.PUBLIC_URL}/images/FoodItems/mushroom_sizzler.jpg` },
    ],
    mostPopular: [
      { name: 'Mixed Sizzler', price: 250, image: `${process.env.PUBLIC_URL}/images/FoodItems/sizzler.jpg` },
      { name: 'Smoky BBQ Platter', price: 240, image: `${process.env.PUBLIC_URL}/images/FoodItems/bbq.jpg` },
      { name: 'Paneer Sizzler', price: 220, image: `${process.env.PUBLIC_URL}/images/FoodItems/paneer_sizzler.jpg` },
    ],
  },
  {
    id: 6,
    name: 'Grill Junction',
    image: `${process.env.PUBLIC_URL}/images/Restaurants/restaurant6.jpg`,
    menu: [
      { name: 'BBQ Chicken Wings', price: 250, image: `${process.env.PUBLIC_URL}/images/FoodItems/wings.jpg` },
      { name: 'Grilled Lamb Chops', price: 240, image: `${process.env.PUBLIC_URL}/images/FoodItems/lamb_chops.jpg` },
      { name: 'Spicy Chicken Skewers', price: 230, image: `${process.env.PUBLIC_URL}/images/FoodItems/skewers.jpg` },
      { name: 'Veg Grill Platter', price: 130, image: `${process.env.PUBLIC_URL}/images/FoodItems/veg_grill.jpg` },
      { name: 'Stuffed Bell Peppers', price: 20, image: `${process.env.PUBLIC_URL}/images/FoodItems/peppers.jpg` },
      { name: 'Grilled Paneer Tikka', price: 220, image: `${process.env.PUBLIC_URL}/images/FoodItems/grilled_paneer.jpg` },
      { name: 'Charred Corn Salad', price: 90, image: `${process.env.PUBLIC_URL}/images/FoodItems/corn_salad.jpg` },
      { name: 'Masala Potato Wedges', price: 100, image: `${process.env.PUBLIC_URL}/images/FoodItems/potato.jpg` },
      { name: 'BBQ Veg Cutlet', price: 140, image: `${process.env.PUBLIC_URL}/images/FoodItems/cutlet.jpg` },
      { name: 'Grilled Mushroom Skillet', price: 135, image: `${process.env.PUBLIC_URL}/images/FoodItems/mushroom.jpg` },
      { name: 'Tandoori Chicken Roll', price: 210, image: `${process.env.PUBLIC_URL}/images/FoodItems/tikka_roll.jpg` },
    ],
    mostPopular: [
      { name: 'BBQ Chicken Wings', price: 250, image: `${process.env.PUBLIC_URL}/images/FoodItems/wings.jpg` },
      { name: 'Grilled Lamb Chops', price: 240, image: `${process.env.PUBLIC_URL}/images/FoodItems/lamb_chops.jpg` },
      { name: 'Grilled Paneer Tikka', price: 220, image: `${process.env.PUBLIC_URL}/images/FoodItems/grilled_paneer.jpg` },
    ],
  }
];

